<a href="https://colab.research.google.com/github/shivamshende02/building-LLMS-from-first-principles/blob/main/Tokens%20and%20Token%20Embeddings/Tokens_and_Token_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!pip install transformers sentence-transformers gensim scikit-learn accelerate peft scipy numpy

In [15]:
from transformers import AutoModelForCausalLM, AutoTokenizer
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=False,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")


config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [18]:
prompt = "Write an email apologizing to shivam for the tragic gardening mishap.Explain how it happened.<|assistant|> "

input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

generation_output = model.generate(
    input_ids=input_ids,
    max_new_tokens=200
)

print(tokenizer.decode(generation_output[0]))


Write an email apologizing to shivam for the tragic gardening mishap.Explain how it happened.<|assistant|> Subject: Sincere Apologies for the Gardening Mishap

Dear Shivam,

I hope this email finds you well. I am writing to express my deepest apologies for the unfortunate incident that occurred in your garden recently. I understand that it must have been a distressing experience for you, and I want to assure you that I take full responsibility for the mishap.

The incident happened on the afternoon of [date], when I was visiting your beautiful garden to discuss a potential collaboration on a community gardening project. As we were discussing the project, I noticed a small patch of your garden that seemed to be in need of some attention. I thought it would be a good idea to help you with the task, as I have some experience in gardening and believe that I could make a positive contribution to your garden.

Unfortunately, things did not go as planned. As I was attempting to


In [19]:
print(input_ids)

tensor([[14350,   385,  4876, 27746,  5281,   304,   528,   440,   314,   363,
           278, 25305,   293, 16423,   292,   286,   728,   481, 29889,  9544,
          7420,   920,   372,  9559, 29889, 32001]], device='cuda:0')


In [20]:
for id in input_ids[0]:
  print(tokenizer.decode(id))

Write
an
email
apolog
izing
to
sh
iv
am
for
the
trag
ic
garden
ing
m
ish
ap
.
Exp
lain
how
it
happened
.
<|assistant|>


In [21]:
generation_output


tensor([[14350,   385,  4876, 27746,  5281,   304,   528,   440,   314,   363,
           278, 25305,   293, 16423,   292,   286,   728,   481, 29889,  9544,
          7420,   920,   372,  9559, 29889, 32001,  3323,   622, 29901,   317,
          3742,   406,  6225, 11763,   363,   278, 19906,   292,   341,   728,
           481,    13,    13, 29928,   799,  1383,   440,   314, 29892,    13,
            13, 29902,  4966,   445,  4876, 14061,   366,  1532, 29889,   306,
           626,  5007,   304,  4653,   590,  6483,   342,  3095, 11763,   363,
           278,   443,  6477,   403, 15134,   393, 10761,   297,   596, 16423,
         10325, 29889,   306,  2274,   393,   372,  1818,   505,  1063,   263,
          1320,  1253,   292,  7271,   363,   366, 29892,   322,   306,   864,
           304,  1223,   545,   366,   393,   306,  2125,  2989, 23134,   363,
           278,   286,   728,   481, 29889,    13,    13,  1576, 15134,  9559,
           373,   278, 17724,   310,   518,  1256,  

In [22]:
print(tokenizer.decode(306))

I


In [23]:
print(tokenizer.decode(777))

some


In [26]:
from transformers import AutoModelForCausalLM, AutoTokenizer

colors_list = [
    '102;194;165','252;141;98','141;160;203',
    '231;138;195', '166;216;84', '255;217;47'
]

def show_tokens(sentence, tokenizer_name):
  tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
  token_ids = tokenizer(sentence).input_ids
  for idx, t in enumerate(token_ids):
    print(
      f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '
    )

In [27]:
text = """
English and CAPITALIZATION
🎵 鸟
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600
"""

In [28]:
show_tokens(text,"bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

[CLS] english and capital ##ization [UNK] [UNK] show _ token ##s false none eli ##f = = > = else : two tab ##s : " " three tab ##s : " " 12 . 0 * 50 = 600 [SEP] 

In [29]:
show_tokens(text, "gpt2")

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]


 English  and  CAP ITAL IZ ATION 
 � � �  � � � 
 show _ t ok ens  False  None  el if  ==  >=  else :  two  tabs :"        "  Three  tabs :  "              " 
 12 . 0 * 50 = 600 
 

In [30]:
show_tokens(text, "google/flan-t5-small")

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

English and CA PI TAL IZ ATION  <unk>  <unk> show _ to ken s Fal s e None  e l if = = > = else : two tab s : " " Three tab s : " " 12. 0 * 50 = 600  </s> 

In [31]:
show_tokens(text, "bigcode/starcoder2-15b")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]


 English  and  CAPITAL IZATION 
 � � �   � � 
 show _ tokens  False  None  elif  ==  >=  else :  two  tabs :"      "  Three  tabs :  "         " 
 1 2 . 0 * 5 0 = 6 0 0 
 

In [32]:
show_tokens(text, "facebook/galactica-1.3b")

tokenizer_config.json:   0%|          | 0.00/166 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.00 [00:00<?, ?B/s]


 English  and  CAP ITAL IZATION 
 � � � �  � � � 
 show _ tokens  False  None  elif   ==   > =  else :  two  t abs : "      "  Three  t abs :   "         " 
 1 2 . 0 * 5 0 = 6 0 0 
 

In [33]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


 
 English and C AP IT AL IZ ATION 
 � � � �  � � � 
 show _ to kens False None elif == >= else : two tabs :"    " Three tabs : "       " 
 1 2 . 0 * 5 0 = 6 0 0 
 

In [35]:
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

tokens = tokenizer('hello world',return_tensors='pt')

output = model(**tokens)[0]

In [36]:
output.shape

torch.Size([1, 4, 384])

In [37]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
hello
 world
[SEP]


In [38]:
output

tensor([[[-3.4837, -0.0382, -0.1863,  ..., -0.1207, -0.2865, -0.0462],
         [ 0.2281,  0.2010,  0.3108,  ..., -0.0393, -0.5177, -0.5506],
         [ 0.2312,  0.4572, -0.1427,  ...,  0.4608, -0.2448, -0.9205],
         [-3.4028, -0.0885, -0.1751,  ..., -0.0073, -0.3034,  0.0101]]],
       grad_fn=<NativeLayerNormBackward0>)

In [1]:
!pip install sentence-transformers==3.0.1 transformers==4.34.0 accelerate==0.31.0 --force-reinstall

from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to text embeddings
vector = model.encode("Best movie ever!")

  Using cached sentence_transformers-3.0.1-py3-none-any.whl.metadata (10 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.5/121.5 kB 7.6 MB/s eta 0:00:00
  Using cached accelerate-0.31.0-py3-none-any.whl.metadata (19 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 5.8 MB/s eta 0:00:00
  Using cached scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
  Using cached huggingface_hub-1.26.0-py3-none-any.whl.metadata (16 kB)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 3.9 MB/s eta 0:00:00
  Using cached setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.1 MB/s eta 0:00:00
Using cached sentence_transformers-3.0.1-py3-none-any.whl (227 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 22.1 MB/s eta 0:00:00
Using cac

/usr/local/lib/python3.12/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


ImportError: cannot import name '_center' from 'numpy._core.umath' (/usr/local/lib/python3.12/dist-packages/numpy/_core/umath.py)

In [2]:

vector.shape

NameError: name 'vector' is not defined